"""x86_64 syscall numbers, I3 deny list, and the demo allow-list.

Binary names are not policy. This table is.
"""

from __future__ import annotations

# Linux x86_64 ABI. Stable; do not use unistd.h at runtime so unit tests
# stay pure Python.
NR: dict[str, int] = {
    "read": 0,
    "write": 1,
    "open": 2,
    "close": 3,
    "stat": 4,
    "fstat": 5,
    "lstat": 6,
    "poll": 7,
    "lseek": 8,
    "mmap": 9,
    "mprotect": 10,
    "munmap": 11,
    "brk": 12,
    "rt_sigaction": 13,
    "rt_sigprocmask": 14,
    "rt_sigreturn": 15,
    "ioctl": 16,
    "pread64": 17,
    "pwrite64": 18,
    "readv": 19,
    "writev": 20,
    "access": 21,
    "pipe": 22,
    "select": 23,
    "sched_yield": 24,
    "mremap": 25,
    "madvise": 28,
    "dup": 32,
    "dup2": 33,
    "nanosleep": 35,
    "getpid": 39,
    "socket": 41,
    "connect": 42,
    "accept": 43,
    "sendto": 44,
    "recvfrom": 45,
    "sendmsg": 46,
    "recvmsg": 47,
    "shutdown": 48,
    "bind": 49,
    "listen": 50,
    "getsockname": 51,
    "getpeername": 52,
    "socketpair": 53,
    "clone": 56,
    "fork": 57,
    "vfork": 58,
    "execve": 59,
    "exit": 60,
    "wait4": 61,
    "kill": 62,
    "uname": 63,
    "fcntl": 72,
    "fsync": 74,
    "fdatasync": 75,
    "truncate": 76,
    "ftruncate": 77,
    "getdents": 78,
    "getcwd": 79,
    "chdir": 80,
    "fchdir": 81,
    "rename": 82,
    "mkdir": 83,
    "rmdir": 84,
    "creat": 85,
    "link": 86,
    "unlink": 87,
    "symlink": 88,
    "readlink": 89,
    "chmod": 90,
    "fchmod": 91,
    "umask": 95,
    "gettimeofday": 96,
    "getrlimit": 97,
    "getuid": 102,
    "syslog": 103,
    "getgid": 104,
    "geteuid": 107,
    "getegid": 108,
    "getppid": 110,
    "getpgrp": 111,
    "getgroups": 115,
    "capget": 125,
    "capset": 126,
    "statfs": 137,
    "fstatfs": 138,
    "arch_prctl": 158,
    "setrlimit": 160,
    "sync": 162,
    "mount": 165,
    "umount2": 166,
    "pivot_root": 155,
    "prctl": 157,
    "ptrace": 101,
    "gettid": 186,
    "futex": 202,
    "getdents64": 217,
    "set_tid_address": 218,
    "fadvise64": 221,
    "clock_gettime": 228,
    "clock_nanosleep": 230,
    "exit_group": 231,
    "waitid": 247,
    "add_key": 248,
    "request_key": 249,
    "keyctl": 250,
    "openat": 257,
    "mkdirat": 258,
    "newfstatat": 262,
    "unlinkat": 263,
    "renameat": 264,
    "linkat": 265,
    "symlinkat": 266,
    "readlinkat": 267,
    "fchmodat": 268,
    "faccessat": 269,
    "pselect6": 270,
    "ppoll": 271,
    "unshare": 272,
    "set_robust_list": 273,
    "utimensat": 280,
    "accept4": 288,
    "dup3": 292,
    "pipe2": 293,
    "perf_event_open": 298,
    "recvmmsg": 299,
    "prlimit64": 302,
    "name_to_handle_at": 303,
    "open_by_handle_at": 304,
    "sendmmsg": 307,
    "setns": 308,
    "process_vm_readv": 310,
    "process_vm_writev": 311,
    "getrandom": 318,
    "bpf": 321,
    "execveat": 322,
    "userfaultfd": 323,
    "rseq": 334,
    "statx": 332,
    "pidfd_send_signal": 424,
    "io_uring_setup": 425,
    "io_uring_enter": 426,
    "io_uring_register": 427,
    "open_tree": 428,
    "move_mount": 429,
    "fsopen": 430,
    "fsconfig": 431,
    "fsmount": 432,
    "fspick": 433,
    "clone3": 435,
    "close_range": 436,
    "openat2": 437,
    "faccessat2": 439,
    "mount_setattr": 442,
}

# clone() flags that create a new namespace. Any of these → EPERM.
CLONE_NEWTIME = 0x00000080
CLONE_NEWNS = 0x00020000
CLONE_NEWCGROUP = 0x02000000
CLONE_NEWUTS = 0x04000000
CLONE_NEWIPC = 0x08000000
CLONE_NEWUSER = 0x10000000
CLONE_NEWPID = 0x20000000
CLONE_NEWNET = 0x40000000
CLONE_NS_MASK = (
    CLONE_NEWTIME
    | CLONE_NEWNS
    | CLONE_NEWCGROUP
    | CLONE_NEWUTS
    | CLONE_NEWIPC
    | CLONE_NEWUSER
    | CLONE_NEWPID
    | CLONE_NEWNET
)

# I3 — always denied. Policy cannot remove these.
DENIED_I3: tuple[str, ...] = (
    "chdir",
    "fchdir",
    "pivot_root",
    "mount",
    "umount2",
    "ptrace",
    "process_vm_readv",
    "process_vm_writev",
    "bpf",
    "perf_event_open",
    "keyctl",
    "add_key",
    "request_key",
    "unshare",
    "setns",
    "clone3",  # flags live in a struct; cannot filter CLONE_NEWUSER
    "socket",  # includes SOCK_RAW; demo profile is network none
    "socketpair",
    "connect",
    "accept",
    "accept4",
    "bind",
    "listen",
    "sendto",
    "sendmsg",
    "sendmmsg",
    "recvfrom",
    "recvmsg",
    "recvmmsg",
    "name_to_handle_at",
    "open_by_handle_at",
    "open_tree",
    "move_mount",
    "fsopen",
    "fsconfig",
    "fsmount",
    "fspick",
    "mount_setattr",
    "userfaultfd",
    "io_uring_setup",
    "io_uring_enter",
    "io_uring_register",
    "syslog",
)

# Demo allow-list for ls/cat + our static/dynamic test programs.
# Each entry is (name, why). fork/clone (sans NEW*) exist so T8 can spawn a
# child that --die-with-parent / the pid ns must reap.
ALLOWED_DEMO: tuple[tuple[str, str], ...] = (
    ("read", "file and pipe IO"),
    ("write", "stdout/stderr and workspace writes"),
    ("open", "legacy open(2); glibc may still emit it"),
    ("close", "fd lifecycle"),
    ("stat", "legacy stat"),
    ("fstat", "fd metadata"),
    ("lstat", "legacy lstat"),
    ("poll", "glibc helper"),
    ("lseek", "cat and ls"),
    ("mmap", "ld.so and brk alternative"),
    ("mprotect", "ld.so RELRO / stack"),
    ("munmap", "ld.so"),
    ("brk", "allocator"),
    ("rt_sigaction", "glibc startup"),
    ("rt_sigprocmask", "glibc startup"),
    ("rt_sigreturn", "signal return"),
    ("ioctl", "TIOCGWINSZ / TCGETS for tty ls; not filtered by arg (residual)"),
    ("pread64", "positioned read"),
    ("pwrite64", "positioned write"),
    ("readv", "vector IO"),
    ("writev", "vector IO"),
    ("access", "existence probes; ENOENT still hides unbound paths"),
    ("pipe", "T8 / glibc"),
    ("select", "glibc helper"),
    ("sched_yield", "glibc"),
    ("mremap", "allocator"),
    ("madvise", "allocator"),
    ("dup", "fd duplication"),
    ("dup2", "fd duplication"),
    ("nanosleep", "T8 sleeper"),
    ("getpid", "self id"),
    ("clone", "fork without CLONE_NEW*; NEWUSER masked off (I3)"),
    ("fork", "T8 child"),
    ("vfork", "legacy spawn"),
    ("execve", "bwrap exec of the tool"),
    ("exit", "thread exit"),
    ("wait4", "reap children"),
    ("uname", "glibc"),
    ("fcntl", "O_CLOEXEC / F_GETFL"),
    ("fsync", "workspace durability"),
    ("fdatasync", "workspace durability"),
    ("truncate", "workspace rewrite"),
    ("ftruncate", "workspace rewrite"),
    ("getdents", "legacy directory list"),
    ("getcwd", "ls"),
    ("rename", "workspace"),
    ("mkdir", "workspace"),
    ("rmdir", "workspace"),
    ("creat", "workspace"),
    ("unlink", "workspace"),
    ("readlink", "ls -l"),
    ("chmod", "workspace mode"),
    ("fchmod", "workspace mode"),
    ("umask", "workspace create"),
    ("gettimeofday", "clock"),
    ("getrlimit", "glibc startup"),
    ("getuid", "ls -n fallback"),
    ("getgid", "ls -n fallback"),
    ("geteuid", "ls"),
    ("getegid", "ls"),
    ("getppid", "die-with-parent observation"),
    ("getpgrp", "session"),
    ("getgroups", "ls"),
    ("capget", "glibc"),
    ("statfs", "ls on some fs"),
    ("fstatfs", "ls on some fs"),
    ("arch_prctl", "FS/GS; mandatory on x86_64"),
    ("setrlimit", "glibc nss sometimes"),
    ("prctl", "PR_SET_NAME; residual: could clear PDEATHSIG"),
    ("gettid", "glibc"),
    ("futex", "glibc locks"),
    ("set_tid_address", "glibc startup"),
    ("fadvise64", "cat readahead"),
    ("clock_gettime", "clock"),
    ("clock_nanosleep", "sleep"),
    ("exit_group", "process exit"),
    ("waitid", "reap"),
    ("openat", "primary open"),
    ("mkdirat", "workspace"),
    ("newfstatat", "primary stat"),
    ("unlinkat", "workspace"),
    ("renameat", "workspace"),
    ("readlinkat", "ls -l"),
    ("fchmodat", "workspace"),
    ("faccessat", "existence"),
    ("pselect6", "glibc"),
    ("ppoll", "glibc"),
    ("set_robust_list", "glibc startup"),
    ("utimensat", "workspace timestamps"),
    ("dup3", "fd duplication"),
    ("pipe2", "O_CLOEXEC pipe"),
    ("prlimit64", "glibc startup"),
    ("getrandom", "stack canary / ld.so"),
    ("execveat", "exec by fd"),
    ("rseq", "glibc 2.35+"),
    ("statx", "modern stat"),
    ("close_range", "glibc 2.34+"),
    ("openat2", "modern open"),
    ("faccessat2", "modern access"),
    ("getdents64", "directory list"),
    ("link", "workspace hardlink"),
    ("linkat", "workspace hardlink"),
)

DENIED_I3_SET = frozenset(DENIED_I3)
ALLOWED_DEMO_NAMES = tuple(name for name, _ in ALLOWED_DEMO)


def number(name: str) -> int:
    try:
        return NR[name]
    except KeyError as exc:
        raise KeyError(f"unknown syscall name {name!r}") from exc
